export default {
  NAVIGATOR_CHANGE: 'NAVIGATOR_CHANGE',
  POST_ADD_SUCCESS: 'POST_ADD_SUCCESS',
  POST_ADD_FAILED: 'POST_ADD_FAILED',
  POST_ADD_RESET: 'POST_ADD_RESET',
  POST_LIST: 'POST_LIST',
  POST_LIST_APPEND: 'POST_LIST_APPEND',
  POST_DELETE: 'POST_DELETE',
  POST_EDIT: 'POST_EDIT',
  POST_GET_CURRENT: 'POST_GET_CURRENT',
  USER_GET_INFO: 'USER_GET_INFO',
  USER_LOGIN: 'USER_LOGIN'
}
